import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import { AuthProvider } from "./context/Auth";

const Roobert = localFont({
  src: [
    {
      path: "./fonts/RoobertTRIAL-Light.otf",
      weight: "300",
    },
    {
      path: "./fonts/RoobertTRIAL-Regular.otf",
      weight: "400",
    },
    {
      path: "./fonts/RoobertTRIAL-Medium.otf",
      weight: "500",
    },
    {
      path: "./fonts/RoobertTRIAL-SemiBold.otf",
      weight: "600",
    },
    {
      path: "./fonts/RoobertTRIAL-Bold.otf",
      weight: "700",
    },
    {
      path: "./fonts/RoobertTRIAL-Heavy.otf",
      weight: "800",
    },
  ],
  variable: "--font-roobert",
});

export const metadata: Metadata = {
  title: "Overstand",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Roobert.className} ${Roobert.variable}`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
